# Packages

library(danstat) 
library(tidyverse)
library(readr)
library(dint)
library(patchwork)
library(gridExtra)
library(forcats)
library(RColorBrewer)
library(furrr)
library(sf)
library(giscoR)
library(viridis)
library(gganimate)
library(tidytable)
library(shiny)

# # if(!require("devtools"))  install.packages("devtools")
# if(!require("ggsflabel")) devtools::install_github("yutannihilation/ggsflabel")
library(ggsflabel)